# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QWidget, QListView, QMainWindow, QApplication
from PyQt5.QtGui import QStandardItemModel, QStandardItem


class ObjectMessageUi(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(646, 80)
        Form.setMaximumSize(QtCore.QSize(16777215, 80))
        Form.setStyleSheet("QWidget::hover{}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.space_0 = QtWidgets.QLabel(Form)
        self.space_0.setMaximumSize(QtCore.QSize(20, 16777215))
        self.space_0.setText("")
        self.space_0.setObjectName("space_0")
        self.horizontalLayout.addWidget(self.space_0)
        self.avatar = QtWidgets.QLabel(Form)
        self.avatar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.avatar.setStyleSheet("background-color:rgb(0, 255, 0);\n"
                                  "border-radius:40")
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")
        self.horizontalLayout.addWidget(self.avatar)
        self.space_1 = QtWidgets.QLabel(Form)
        self.space_1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.space_1.setText("")
        self.space_1.setObjectName("space_1")
        self.horizontalLayout.addWidget(self.space_1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(Form)
        self.name.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.content = QtWidgets.QWidget(Form)
        self.content.setObjectName("content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.message = QtWidgets.QLabel(self.content)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.message.setFont(font)
        self.message.setObjectName("message")
        self.verticalLayout_2.addWidget(self.message)
        self.verticalLayout.addWidget(self.content)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name.setText(_translate("Form", "hsx"))
        self.message.setText(_translate("Form", "hsxnb"))


class ObjMessage(QWidget):
    def __init__(self,message_pak=''):
        super(ObjMessage, self).__init__()
        self.ui = ObjectMessageUi()
        self.ui.setupUi(self)
        if len(message_pak)!=0:
            pass#TODO


class InfoItemUi(object):
    def setupUi(self, list_item):
        list_item.setObjectName("list_item")
        list_item.setMaximumSize(200,70)
        list_item.setMinimumSize(200,70)
        list_item.setStyleSheet("background:rgb(255, 255, 255)")
        self.horizontalLayout = QtWidgets.QHBoxLayout(list_item)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(list_item)
        self.widget.setMinimumSize(QtCore.QSize(70, 0))
        self.widget.setMaximumSize(QtCore.QSize(70, 70))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.delete_2 = QtWidgets.QPushButton(self.widget)
        self.delete_2.setStyleSheet("border:none")
        self.delete_2.setMinimumSize(QtCore.QSize(15, 70))
        self.delete_2.setMaximumSize(QtCore.QSize(15, 70))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.delete_2.setFont(font)
        self.delete_2.setObjectName("delete_2")
        self.horizontalLayout_2.addWidget(self.delete_2)
        self.headPic = QtWidgets.QLabel(self.widget)
        self.headPic.setMinimumSize(QtCore.QSize(50, 50))
        self.headPic.setMaximumSize(QtCore.QSize(50, 50))
        self.headPic.setStyleSheet("border-radius:25px;\n"
                                   "background:rgb(0, 0, 0)rgb(255, 255, 255)rgb(161, 161, 161);\n"
                                   "")
        self.headPic.setText("")
        self.headPic.setObjectName("headPic")
        self.horizontalLayout_2.addWidget(self.headPic)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nickname = QtWidgets.QLabel(list_item)
        # self.nickname.setMinimumSize(QtCore.QSize(425, 35))
        # self.nickname.setMaximumSize(QtCore.QSize(425, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.nickname.setFont(font)
        self.nickname.setObjectName("nickname")
        self.verticalLayout.addWidget(self.nickname)
        self.snapshot = QtWidgets.QLabel(list_item)
        self.snapshot.setMinimumSize(QtCore.QSize(425, 16))
        self.snapshot.setMaximumSize(QtCore.QSize(425, 16))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(8)
        self.snapshot.setFont(font)
        self.snapshot.setStyleSheet("color:#5B5B5B")
        self.snapshot.setObjectName("snapshot")
        self.verticalLayout.addWidget(self.snapshot)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(list_item)
        QtCore.QMetaObject.connectSlotsByName(list_item)

    def retranslateUi(self, list_item):
        _translate = QtCore.QCoreApplication.translate
        list_item.setWindowTitle(_translate("list_item", "Form"))
        self.delete_2.setText(_translate("list_item", "X"))
        self.nickname.setText(_translate("list_item", "群聊助手"))
        self.snapshot.setText(_translate("list_item", "message"))


class InfoItem(QWidget):
    def __init__(self):
        super(InfoItem, self).__init__()
        self.ui = InfoItemUi()
        self.ui.setupUi(self)


class ChatWindowUi(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.setWindowOpacity(1.0)
        Widget.setMinimumSize(1000, 618)
        Widget.resize(1000, 618)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoItemList = MessageListView()
        self.infoItemList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.infoItemList.setObjectName("infoItemList")
        self.horizontalLayout.addWidget(self.infoItemList)
        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.messageWindow = MessageListWindow(self)
        self.messageWindow.setObjectName("messageWindow")
        self.verticalLayout.addWidget(self.messageWindow)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.messageInput = QtWidgets.QLineEdit(self.widget)
        self.messageInput.setObjectName("messageInput")
        self.horizontalLayout_2.addWidget(self.messageInput)
        self.send = QtWidgets.QPushButton(self.widget)
        self.send.setObjectName("send")
        self.horizontalLayout_2.addWidget(self.send)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.send.setText(_translate("Widget", "发送"))

    # def update_chatWindow(self):


class MessageListView(QListView):
    def __init__(self):
        super(MessageListView, self).__init__()
        self._model = QStandardItemModel(self)
        self.setModel(self._model)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        for i in range(15):
            item = QStandardItem()
            self._model.appendRow(item)

            index = self._model.indexFromItem(item)
            widget = InfoItem()
            widget.ui.snapshot.setText("信息" + str(i))
            widget.ui.delete_2.clicked.connect(self.remove)
            widget.ui.delete_2.setProperty("item", item)

            item.setSizeHint(QSize(190, 70))
            self.setIndexWidget(index, widget)

    def update_list(self):
        pass  # TODO

    def remove(self):
        item = self.sender().property("item")
        index = self._model.indexFromItem(item).row()
        self._model.removeRow(index)

    def swtich(self):
        pass

class MessageListWindow(QListView):
    def __init__(self, chat_window):
        super(MessageListWindow, self).__init__()
        self._model = QStandardItemModel(self)
        self.setModel(self._model)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        for i in range(15):
            item = QStandardItem()
            self._model.appendRow(item)

            index = self._model.indexFromItem(item)
            if i % 2 == 0:
                widget = ObjMessage()
            else:
                widget = ObjMessage()
                widget.setLayoutDirection(QtCore.Qt.RightToLeft)
                widget.ui.message.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
                widget.ui.name.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
            item.setSizeHint(QSize(600,80))

            self.setIndexWidget(index, widget)

            item.setSelectable(False)
class ChatWindow(QWidget):
    def __init__(self,app):
        super(ChatWindow, self).__init__()
        self.ui = ChatWindowUi()
        self.ui.setupUi(self)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    chatwindow = ChatWindow(app)
    chatwindow.show()
    sys.exit(app.exec_())

