# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lucifer/Code/QtProjects/Chat/widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QWidget, QApplication


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(760, 100)
        Widget.setStyleSheet("background:white;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setMaximumSize(QtCore.QSize(60, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.avatar = QtWidgets.QLabel(self.widget)
        self.avatar.setMinimumSize(QtCore.QSize(50, 50))
        self.avatar.setMaximumSize(QtCore.QSize(50, 50))
        self.avatar.setStyleSheet("background:rgba(159, 255, 148, 158);\n"
                                  "border-radius:25;")
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")
        self.horizontalLayout_2.addWidget(self.avatar)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalWidget = QtWidgets.QWidget(Widget)
        self.verticalWidget.setObjectName("verticalWidget")
        self.content = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.content.setContentsMargins(0, 0, 0, 0)
        self.content.setSpacing(0)
        self.content.setObjectName("content")
        self.nick_name = QtWidgets.QLabel(self.verticalWidget)
        self.nick_name.setMinimumSize(QtCore.QSize(0, 30))
        self.nick_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.nick_name.setObjectName("nick_name")
        self.content.addWidget(self.nick_name)
        self.msg = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(18)
        self.msg.setFont(font)
        self.msg.setObjectName("msg")
        self.msg.setStyleSheet('color:black')
        self.content.addWidget(self.msg)
        self.horizontalLayout.addWidget(self.verticalWidget)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Form"))
        self.nick_name.setText(_translate("Widget", "黄生鲜"))
        self.msg.setText(_translate("Widget", "测试"))


class msg_item(QWidget):
    def __init__(self):
        super(QWidget, self).__init__()
        self.ui = Ui_Widget()
        self.ui.setupUi(self)
        self.ui.msg.setEnabled(False)
        self.setFocusPolicy(QtCore.Qt.NoFocus)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = msg_item()
    w.setWindowFlag(QtCore.Qt.FramelessWindowHint)
    w.show()
    sys.exit(app.exec_())
