# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lucifer/Code/QtProjects/Chat/widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(240, 70)
        Widget.setMinimumSize(QtCore.QSize(240, 70))
        Widget.setMaximumSize(QtCore.QSize(240, 70))
        Widget.setStyleSheet("background:white;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close_btn = QtWidgets.QLabel(Widget)
        self.close_btn.setMinimumSize(QtCore.QSize(20, 240))
        self.close_btn.setMaximumSize(QtCore.QSize(20, 240))
        self.close_btn.setStyleSheet("background:rgb(122, 121, 124)")
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.avatar = QtWidgets.QLabel(Widget)
        self.avatar.setMinimumSize(QtCore.QSize(40, 40))
        self.avatar.setMaximumSize(QtCore.QSize(40, 40))
        self.avatar.setStyleSheet("background:rgb(82, 255, 53);\n"
"border-radius:20;")
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")
        self.horizontalLayout.addWidget(self.avatar)
        self.spacer_0 = QtWidgets.QLabel(Widget)
        self.spacer_0.setMinimumSize(QtCore.QSize(5, 0))
        self.spacer_0.setMaximumSize(QtCore.QSize(5, 16777215))
        self.spacer_0.setText("")
        self.spacer_0.setObjectName("spacer_0")
        self.horizontalLayout.addWidget(self.spacer_0)
        self.chat_preview = QtWidgets.QVBoxLayout()
        self.chat_preview.setSpacing(0)
        self.chat_preview.setObjectName("chat_preview")
        self.name = QtWidgets.QLabel(Widget)
        self.name.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.name.setFont(font)
        self.name.setStyleSheet("")
        self.name.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.name.setObjectName("name")
        self.chat_preview.addWidget(self.name, 0, QtCore.Qt.AlignBottom)
        self.spacer_1 = QtWidgets.QLabel(Widget)
        self.spacer_1.setMaximumSize(QtCore.QSize(16777215, 10))
        self.spacer_1.setStyleSheet("")
        self.spacer_1.setText("")
        self.spacer_1.setObjectName("spacer_1")
        self.chat_preview.addWidget(self.spacer_1, 0, QtCore.Qt.AlignTop)
        self.msg_preview = QtWidgets.QLabel(Widget)
        self.msg_preview.setMinimumSize(QtCore.QSize(0, 30))
        self.msg_preview.setStyleSheet("\n"
"color:grey")
        self.msg_preview.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.msg_preview.setObjectName("msg_preview")
        self.chat_preview.addWidget(self.msg_preview, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addLayout(self.chat_preview)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Form"))
        self.name.setText(_translate("Widget", "兜率宫"))
        self.msg_preview.setText(_translate("Widget", "黄生鲜：来张色图"))
